export const DefaultFun = {
  // Integers
  AddInteger: "addInteger",
  SubtractInteger: "subtractInteger",
  MultiplyInteger: "multiplyInteger",
  DivideInteger: "divideInteger",
  QuotientInteger: "quotientInteger",
  RemainderInteger: "remainderInteger",
  ModInteger: "modInteger",
  EqualsInteger: "equalsInteger",
  LessThanInteger: "lessThanInteger",
  LessThanEqualsInteger: "lessThanEqualsInteger",
  // Bytestrings
  AppendByteString: "appendByteString",
  ConsByteString: "consByteString",
  SliceByteString: "sliceByteString",
  LengthOfByteString: "lengthOfByteString",
  IndexByteString: "indexByteString",
  EqualsByteString: "equalsByteString",
  LessThanByteString: "lessThanByteString",
  LessThanEqualsByteString: "lessThanEqualsByteString",
  // Cryptography and hashes
  Sha2_256: "sha2_256",
  Sha3_256: "sha3_256",
  Blake2b_256: "blake2b_256",
  VerifyEd25519Signature: "verifyEd25519Signature",
  VerifyEcdsaSecp256k1Signature: "verifyEcdsaSecp256k1Signature",
  VerifySchnorrSecp256k1Signature: "verifySchnorrSecp256k1Signature",
  // Strings
  AppendString: "appendString",
  EqualsString: "equalsString",
  EncodeUtf8: "encodeUtf8",
  DecodeUtf8: "decodeUtf8",
  // Bool
  IfThenElse: "ifThenElse",
  // Unit
  ChooseUnit: "chooseUnit",
  // Tracing
  Trace: "trace",
  // Pairs
  FstPair: "fstPair",
  SndPair: "sndPair",
  // Lists
  ChooseList: "chooseList",
  MkCons: "mkCons",
  HeadList: "headList",
  TailList: "tailList",
  NullList: "nullList",
  // Data
  ChooseData: "chooseData",
  ConstrData: "constrData",
  MapData: "mapData",
  ListData: "listData",
  IData: "iData",
  BData: "bData",
  UnConstrData: "unConstrData",
  UnMapData: "unMapData",
  UnListData: "unListData",
  UnIData: "unIData",
  UnBData: "unBData",
  EqualsData: "equalsData",
  SerialiseData: "serialiseData",
  // Misc monomorphized constructors
  MkPairData: "mkPairData",
  MkNilData: "mkNilData",
  MkNilPairData: "mkNilPairData",
};
